### ISSUE TITLE
Barrel management and the extName documentation

### ISSUE THREAD

**Issue by Downchuck** [kubb-labs/kubb#1087]
### What is the type of issue?

Documentation is confusing

### What is the issue?

I've come up against two issues in the Zod plugin working with processing:

The extName only applies to barrel files, and the barrel files are processed after the buildEnd hook.

```
    pluginZod({
      output: {
        path: "./parser",
        extName: ".js",
        exportType: "barrel",
      }, ...
```

```
const pluginZodJsdoc = createPlugin((options) => {
  return {
    name: "plugin-zod-jsdoc",
    key: ['plugin-zod-jsdoc'],
    options,
    pre: [pluginZodName],
    async buildEnd() {
   ...
```

Arguably, the extName only applies to barrel files, and the barrel files are not buildEnd for a pre-hook.

That said, I'd expect that the "operations.ts" file generated by pluginZod would use import statements with the extName applied, and that a plugin with a pre would wait until after the barrel file is generate before triggering the buildEnd hook on the plugin.

**Comment by stijnvanhulle** [comment]
@Downchuck This has been resolved as part of v3 of Kubb, see https://v3.kubb.dev/getting-started/configure#output-extension. We will use `output.extension` instead of `extName`, this will make it possible to override the extension and make sure we use the same extname for every file created by Kubb.
