### ISSUE TITLE
Skiptoken Error

### ISSUE THREAD

**Issue by jrwpatterson** [kubb-labs/kubb#1346]
### What version of `kubb` is running?

2.28.1

### What platform is your computer?

macos

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

https://github.com/TanStack/query/releases/tag/v5.59.13

### What steps can reproduce the bug?

the https://github.com/TanStack/query/releases/tag/v5.59.11 release of React Query breaks the types around the skiptoken. This creates typeerrors throughout the project

### How often does this bug happen?

None

### What is the expected behavior?

Not to have typeerrors

**Comment by andrewvy** [comment]
I believe this might be fixed in the new upcoming version of kubb:

https://github.com/kubb-labs/kubb/blob/0e6dfc6ec5fb99a859867394d13b9cdd24b10a46/packages/plugin-react-query/src/components/SuspenseQuery.tsx#L97-L118

This outputs to use `UseSuspenseQueryOptions`, which now excludes `skipToken` and seems to typecheck correctly

However kubb v2 uses `QueryObserverOptions`, which is incompatible for suspense queries (as `skipToken` is no longer a type-supported option)

https://github.com/kubb-labs/kubb/blob/e8af6658730c547c619bc836ddce3bbf11380c09/packages/swagger-tanstack-query/src/components/Query.tsx#L65-L69

I think a fix would need to be backported to v2 to additionally support swapping to `UseSuspenseQueryOptions` when generating a suspense query.

**Comment by stijnvanhulle** [comment]
Resolved with kubb v`2.28.3`
